name = "counter-test"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[[durable_objects.bindings]]
name = "COUNTER_ROOM"
class_name = "CounterRoom"

[[durable_objects.bindings]]
name = "MATCHMAKER"
class_name = "Matchmaker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CounterRoom", "Matchmaker"]

[assets]
directory = "./public"
binding = "ASSETS"