name = "counter-test"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[[durable_objects.bindings]]
name = "TICK_ROOM"
class_name = "TickRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TickRoom"]

[assets]
directory = "./public"
binding = "ASSETS"